<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ps_quantsearch"
 *
 * Auto generated by Extension Builder 2018-11-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'PS Qwant Search',
	'description' => 'Integrate internal Qwant search',
	'category' => 'plugin',
	'author' => 'Pierre Frumillon',
	'author_email' => 'pf@pistil-studio.fr',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);